language: bash
services:
- docker
env:
  global:
  - DEPLOY_USER=travis
  - DEPLOY_SERVER=206.189.130.193
  - DEPLOY_PATH=/home/travis
before_install:
- openssl aes-256-cbc -K $encrypted_d3c148061e7a_key -iv $encrypted_d3c148061e7a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf remote.tar
before_script:
- scripts/docker-build.sh docker witbix
- scripts/traefik-setup.sh local
script:
- scripts/drupal-build.sh dev
deploy:
- provider: script
  script: scripts/deploy.sh ${DEPLOY_USER} ${DEPLOY_SERVER} ${DEPLOY_PATH} stage
  skip_cleanup: true
  on:
    branch: stage-test
- provider: script
  script: scripts/deploy.sh ${DEPLOY_USER} ${DEPLOY_SERVER} ${DEPLOY_PATH} master
  skip_cleanup: true
  on:
    branch: prod-test
