language: bash
services:
- docker
env:
  global:
  - DEPLOY_USER=travis
  - DEPLOY_SERVER=35.200.141.209
  - DEPLOY_PATH=/home/travis/witbix
before_install:
- openssl aes-256-cbc -K $encrypted_d3c148061e7a_key -iv $encrypted_d3c148061e7a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
before_script:
- scripts/docker-build.sh
- scripts/traefik-setup.sh 'local'
script:
- if [ ${TRAVIS_BRANCH} == 'dev' ] || [ ${TRAVIS_BRANCH} == 'stage' ]; then scripts/drupal-build.sh
  ${TRAVIS_BRANCH}; fi
deploy:
- provider: script
  script: scripts/deploy.sh ${DEPLOY_USER} ${DEPLOY_SERVER} ${DEPLOY_PATH} stage
  skip_cleanup: true
  on:
    branch: stage
- provider: script
  script: scripts/deploy.sh ${DEPLOY_USER} ${DEPLOY_SERVER} ${DEPLOY_PATH} prod
  skip_cleanup: true
  on:
    branch: prod
