version: "3.5"

services:

#  local-persist:
#    image: cwspear/docker-local-persist-volume-plugin
#    volumes:
#      - /run/docker/plugins/:/run/docker/plugins/

  php:
    container_name: ${PROJECT_NAME}
    build: ./docker/drupal-tools
    image: dbjpanda/drupal-tools
    restart: always
    working_dir: /var/www/${PROJECT_NAME}
    volumes:
      - ./code/drupal:/var/www/${PROJECT_NAME}:cached
      - staticfiles:/tmp/files
    environment:
      - PROJECT_NAME
      - DRUPAL_VERSION
      - MYSQL_HOSTNAME
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
    networks:
      - drupal

  nginx:
    container_name: ${PROJECT_NAME}.nginx
    build: ./docker/nginx
    image: witbix/nginx
    restart: always
    working_dir: /var/www/${PROJECT_NAME}
    volumes:
      - ./code/drupal:/var/www/${PROJECT_NAME}:cached
      - staticfiles:/tmp/files
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    environment:
      - PROJECT_NAME
      - DOMAIN_NAME
    networks:
      - drupal

  mariadb:
    container_name: ${PROJECT_NAME}.mariadb
#    build: ./docker/mariadb
    image: witbix/mariadb
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - drupal


volumes:

#  drupal:
#    driver: local-persist
#    driver_opts:
#      mountpoint: $PWD/src



#  drupal:
#    driver: local
#    driver_opts:
#      type: none
#      device: $PWD/code/drupal
#      o: bind
  database:
    driver: local
  staticfiles:
    driver: local

networks:
  drupal:
    external:
     name: ${NETWORK_NAME}
