version: "3.4"

services:

  php:
    container_name: ${PROJECT_NAME}
#    build: ./docker/php
    image: witbix/php
    restart: always
    working_dir: /var/www/${PROJECT_NAME}
    volumes:
      - ./code/drupal:/var/www/${PROJECT_NAME}:cached
      - files:/tmp/files:cached
    environment:
      - ENVIRONMENT
      - PROJECT_NAME
      - DRUPAL_VERSION
      - DRUPAL_USERNAME
      - DRUPAL_PASSWORD
      - MYSQL_HOSTNAME
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - GITHUB_TOKEN
    networks:
      - drupal

  nginx:
    container_name: ${PROJECT_NAME}.nginx
#    build: ./docker/nginx
    image: witbix/nginx
    restart: always
    working_dir: /var/www/${PROJECT_NAME}/web
    volumes:
      - ./code/drupal/web/:/var/www/${PROJECT_NAME}/web/:ro,cached
      - files:/tmp/files:cached
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    environment:
      - PROJECT_NAME
      - DRUPAL_VERSION
      - DOMAIN_NAME
    networks:
      - drupal
    depends_on:
      - php

  mariadb:
    container_name: ${PROJECT_NAME}.mariadb
#    build: ./docker/mariadb
    image: witbix/mariadb
    restart: always
    volumes:
      - database:/var/lib/mysql:cached
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - REPL_ENABLE
      - REPL_USER
      - REPL_PASS
    networks:
      - drupal

#  redis:
#    container_name: ${PROJECT_NAME}.redis
#    image: witbix/redis
#    networks:
#      - drupal

volumes:
  database:
    driver: local
    name: ${PROJECT_NAME}-database
  files:
    driver: local
    name: ${PROJECT_NAME}-files

networks:
  drupal:
    external:
     name: ${NETWORK_NAME}
