# ----Production Node----
FROM alpine:3.8 As prod

ENV PROJECT_NAME=test \
    DRUPAL_VERSION=8 \
    MYSQL_HOSTNAME=test.mariadb \
    MYSQL_DATABASE=drupal \
    MYSQL_USER=test \
    MYSQL_PASSWORD=pass \
    MYSQL_PORT=3306 \
    ENVIRONMENT=dev

RUN set -ex \
    && addgroup -g 2000 www-php \
    && adduser -D -u 2000 -G www-php www-php \
    && apk --no-cache add \
            php7-fpm \
            php7-ctype \
            mysql-client \
            php7-curl \
            php7-dom \
            php7-ftp \
            php7-gd \
            php7-json \
            php7-mbstring \
            php7-pdo \
            php7-pdo_mysql \
            php7-session \
            php7-simplexml \
            php7-tokenizer \
            php7-xml \
            php7-xmlwriter \
            php7-opcache \
            php7 \
    && chmod u+s /usr/sbin/php-fpm7 \
    && mkdir -m o+w /tmp/files

COPY conf.d/opcache.ini /etc/php7/conf.d
COPY php-fpm.d /etc/php7/php-fpm.d
COPY --chown=www-php drupal-templates /home/deploy/drupal-templates
COPY entrypoint.sh /


EXPOSE 9000
USER www-php:www-php

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm7","-F"]






# ----Development Node----
FROM prod AS dev
USER root:root
RUN set -ex \
    && apk --no-cache add \
            php7-xdebug \
            zip \
            git \
            composer \
    && wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar \
    && chmod +x /usr/local/bin/drush \
    && wget -O /usr/local/bin/drupal https://drupalconsole.com/installer \
    && chmod +x /usr/local/bin/drupal \
    && composer global require hirak/prestissimo

COPY conf.d/xdebug.ini /etc/php7/conf.d
