FROM alpine:3.8



RUN set -ex \
    && addgroup -g 2000 deploy \
    && adduser -D -u 2000 -G root -s /bin/sh deploy \
    && echo '@em http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories  \
    && echo '@ec http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories \
    && echo '@et http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories \
    && apk --no-cache add \
            php7-fpm \
            php7-ctype \
            mysql-client \
            php7-curl \
            php7-dom \
            php7-ftp \
            php7-gd \
            php7-json \
            php7-mbstring \
            php7-pdo \
            php7-pdo_mysql \
            php7-session \
            php7-simplexml \
            php7-tokenizer \
            php7-xml \
            php7-opcache \
            php7-xdebug \
            php7 \
            zip \
            git \
            composer@ec \
    && chmod u+s /usr/sbin/php-fpm7 \
    && wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar \
    && chmod +x /usr/local/bin/drush \
    && wget -O /usr/local/bin/drupal https://drupalconsole.com/installer \
    && chmod +x /usr/local/bin/drupal


COPY conf.d /etc/php7/conf.d
COPY php-fpm.d /etc/php7/php-fpm.d
EXPOSE 9000


# Run everything as user `deploy` from this step onwards.
#USER deploy
#RUN composer global require hirak/prestissimo


CMD ["php-fpm7","-F"]

